apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: nocodeml
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: worker
          env:
            - name: NOCODEML_CELERY_QUEUE
              value: training-gpu
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "4"
              memory: 16Gi
              nvidia.com/gpu: "1"
